"""empty message

Revision ID: 24dacc84b13c
Revises: 36bcd7bc68ee
Create Date: 2023-11-21 14:26:36.805035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24dacc84b13c'
down_revision = '36bcd7bc68ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingrediants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_number', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingrediants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('item_number')

    # ### end Alembic commands ###
