"""empty message

Revision ID: 26550065d8dd
Revises: d4c1ef7b1a81
Create Date: 2024-02-05 16:53:31.691676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26550065d8dd'
down_revision = 'd4c1ef7b1a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingrediants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('ingrediants', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
