"""empty message

Revision ID: 6fef7a7b7377
Revises: 7ca0d0ed6257
Create Date: 2023-11-09 00:11:36.719033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fef7a7b7377'
down_revision = '7ca0d0ed6257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_recipes')
    op.drop_table('followers')
    op.drop_table('recipe_categories')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('categories_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['category'])
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('categories_name_key', ['name'])
        batch_op.drop_column('recipe_id')
        batch_op.drop_column('category')

    op.create_table('recipe_categories',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='recipe_categories_category_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='recipe_categories_recipe_id_fkey')
    )
    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='followers_follower_id_fkey'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name='followers_following_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='followers_pkey')
    )
    op.create_table('favorite_recipes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='favorite_recipes_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorite_recipes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_recipes_pkey')
    )
    # ### end Alembic commands ###
