"""empty message

Revision ID: 91dd91a31125
Revises: f0304f130a1e
Create Date: 2023-11-09 20:52:41.023222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91dd91a31125'
down_revision = 'f0304f130a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False)) 
        batch_op.create_unique_constraint(None, ['username'])

    # connection = op.get_bind()
    # connection.execute(sa.text("UPDATE users SET username = 'jhon' WHERE id = 1"))
    # connection.execute(sa.text("UPDATE users SET username = 'jane' WHERE id = 2"))

    # with op.batch_alter_table('recipes', schema=None) as batch_op:
    #     batch_op.alter_column('category_id', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
