"""empty message

Revision ID: a888a0efc05c
Revises: 6fef7a7b7377
Create Date: 2023-11-09 00:43:45.045327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a888a0efc05c'
down_revision = '6fef7a7b7377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_recipe_id_fkey', type_='foreignkey')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('categories_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
