"""empty message

Revision ID: f0304f130a1e
Revises: a888a0efc05c
Create Date: 2023-11-09 12:07:47.806914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0304f130a1e'
down_revision = 'a888a0efc05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer()), nullable=False)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # connection = op.get_bind()
    # connection.execute(sa.text("UPDATE recipes SET category_id = 1"))

    # with op.batch_alter_table('recipes', schema=None) as batch_op:
    #     batch_op.alter_column('category_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
